// Since we don't want to include a selection.json in our distribution bundle we've come up with the following solution:
// - If the contents of selection.json ever change just uncomment the import below and start Storybook
// - Open the console, the generated icon types should be logged there
// - Copy these to this file and outcomment the import again
// The contents copied from the console while cause of bunch of ESLint errors, but don't worry, you can fix these
// automatically by running npm run lint:js -- --fix in the console
// I know this solution is a little bit weird but it's still better than including a 40 kb JSON file in our bundle
// If you manage to come up with a better solution don't hesitate to implement it!
// import '../../../utils/getIconTypes';

export const ICON_TYPES = {
    CABLE: 'Cable',
    CALENDAR: 'Calendar',
    CALENDARACCEPT: 'CalendarAccept',
    CALENDARDECLINE: 'CalendarDecline',
    CARDS: 'Cards',
    CHANGE: 'Change',
    CHECK: 'Check',
    CHEVRONDOWN: 'ChevronDown',
    CHEVRONFIRST: 'ChevronFirst',
    CHEVRONLAST: 'ChevronLast',
    CHEVRONLEFT: 'ChevronLeft',
    CHEVRONRIGHT: 'ChevronRight',
    CHEVRONUP: 'ChevronUp',
    CLOCK: 'Clock',
    COMMUNICATIONMAIL: 'CommunicationMail',
    COMMUNICATIONPHONE: 'CommunicationPhone',
    CROSS: 'Cross',
    DROPDOWN: 'DropDown',
    DROPLEFT: 'DropLeft',
    DROPRIGHT: 'DropRight',
    DROPUP: 'DropUp',
    EVENTGENERIC: 'EventGeneric',
    EVENTREDCARD: 'EventRedCard',
    EVENTYELLOWCARD: 'EventYellowCard',
    FLAG: 'Flag',
    GEAR: 'Gear',
    INDICATOR: 'Indicator',
    LIGHTBULB: 'Lightbulb',
    LOCKOFF: 'LockOff',
    LOCKON: 'LockOn',
    LOGOUT: 'Logout',
    MATCHCANCEL: 'MatchCancel',
    MATCHCOMPA: 'MatchCompA',
    MATCHCOMPB: 'MatchCompB',
    MATCHCUP: 'MatchCup',
    MATCHDELETE: 'MatchDelete',
    MATCHOWN: 'MatchOwn',
    MATCHRESUME: 'MatchResume',
    MENU: 'Menu',
    MINUS: 'Minus',
    MOVEALL: 'MoveAll',
    MOVELEFTRIGHT: 'MoveLeftRight',
    MOVEUPDOWN: 'MoveUpDown',
    OPTIONS: 'Options',
    PENCIL: 'Pencil',
    PLACEHOLDER: 'Placeholder',
    PLANE: 'Plane',
    PLUS: 'Plus',
    POSTBOXIN: 'PostboxIn',
    POSTBOXOUT: 'PostboxOut',
    PRODUCTADS: 'ProductAds',
    PRODUCTAVG: 'ProductAVG',
    PRODUCTBOEKHOUDING: 'ProductBoekhouding',
    PRODUCTCONTRIBUTIE: 'ProductContributie',
    PRODUCTDATASERVICE: 'ProductDataservice',
    PRODUCTDWF: 'ProductDWF',
    PRODUCTMOBIEL: 'ProductMobiel',
    PRODUCTOPLEIDINGEN: 'ProductOpleidingen',
    PRODUCTTOERNOOIEN: 'ProductToernooien',
    PRODUCTTRAININGEN: 'ProductTrainingen',
    PRODUCTTV: 'ProductTV',
    PRODUCTVRIJWILLIGERS: 'ProductVrijwilligers',
    PRODUCTWEBSITE: 'ProductWebsite',
    QUESTION: 'Question',
    ROUNDCHECK: 'RoundCheck',
    ROUNDCROSS: 'RoundCross',
    ROUNDHELP: 'RoundHelp',
    ROUNDINFO: 'RoundInfo',
    ROUNDMINUS: 'RoundMinus',
    ROUNDPLUS: 'RoundPlus',
    SEARCH: 'Search',
    SELECT: 'Select',
    SHARE: 'Share',
    SHIELD: 'Shield',
    SHIRT: 'Shirt',
    SPORTATLETIEK: 'SportAtletiek',
    SPORTBASKETBAL: 'SportBasketbal',
    SPORTHANDBAL: 'SportHandbal',
    SPORTHOCKEY: 'SportHockey',
    SPORTHONKBAL: 'SportHonkbal',
    SPORTJUDO: 'SportJudo',
    SPORTKORFBAL: 'SportKorfbal',
    SPORTKRACHT: 'SportKracht',
    SPORTREDDINGSBRIGADE: 'SportReddingsbrigade',
    SPORTVOETBAL: 'SportVoetbal',
    SPORTVOLLEYBAL: 'SportVolleybal',
    SPORTZWEMMEN: 'SportZwemmen',
    STATUSALERT: 'StatusAlert',
    STATUSCANCELED: 'StatusCanceled',
    STATUSCONCEPT: 'StatusConcept',
    STATUSCONCEPTALERT: 'StatusConceptAlert',
    STATUSDONE: 'StatusDone',
    STATUSERROR: 'StatusError',
    STATUSSUSPENDED: 'StatusSuspended',
    TRASHCAN: 'Trashcan',
    USER: 'User',
    USERDOUBLE: 'UserDouble',
    VISIBILITYOFF: 'VisibilityOff',
    VISIBILITYON: 'VisibilityOn',
    WORLD: 'World',
};

export default ICON_TYPES;
