# Configuration based on:
# - https://circleci.com/docs/2.0/language-javascript/
# If you want to learn more about YAML check out the following documentation:
# - https://learnxinyminutes.com/docs/yaml/
version: 2.1
default: &defaults
    working_directory: ~/dexels-ui-kit
    docker:
        - image: circleci/node:10.16.0

jobs:
    install_dependencies:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Update NPM
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: Install dependencies
                command: |
                    npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
    lint_javascript:
        <<: *defaults
        steps:
            - checkout
            - run:
                command: 'ls -al'
            - run:
                name: Run ESLint
                command: 'npm run lint:js -- --format junit --output-file reports/junit/js-lint-results.xml'
            - store_test_results:
                path: reports/junit
            - store_artifacts:
                path: reports/junit
    lint_css:
        <<: *defaults
        steps:
            - checkout
            - run:
                command: echo 'Linted some css'

workflows:
    install_dependencies_and_lint:
        jobs:
            - install_dependencies
            - lint_javascript:
                requires:
                    - install_dependencies
            - lint_css:
                requires:
                    - install_dependencies
